environment:
  matrix:
    # Nightly channel
    - RUST: nightly
      BITS: 32
    - RUST: nightly
      BITS: 64

install:
  - IF "%BITS%" == "32" SET ARCH=i686
  - IF "%BITS%" == "64" SET ARCH=x86_64
  - SET RUST_URL=https://static.rust-lang.org/dist/rust-%RUST%-%ARCH%-pc-windows-msvc.exe
  - ps: Start-FileDownload $Env:RUST_URL -FileName rust-dist.exe
  - rust-dist.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - IF "%BITS%" == "32" CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\vcvars32.bat"
  - IF "%BITS%" == "64" CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
  - rustc -V
  - cargo -V

build: false

test_script:
  - rustc --version
  - cargo test
  - cd examples
  - cargo run -- ../assets/test.mp3
